data: 
  data_dir: data/humpback-whale-identification

train:
  data: 
    data_dir: data/humpback-whale-identification

  net:
    backbone_name: levit_128
    pretrained: true
    embedding_size: 384
    num_classes: 4604

  loss:
    num_classes: 4604
    embedding_size: 384
    margin: 16
    scale: 32

  trainer: 
    devices: [1]
    max_epochs: 1
    enable_checkpointing: true
    enable_progress_bar: true
    accumulate_grad_batches: 1
    gradient_clip_val: 1
    default_root_dir: runs/


  seed: 42
  head_lr: 0.001
  backbone_lr: 0.0001
  batch_size: 256
  save_emb_db_path: runs/lightning_logs
  device: cuda:1

infer: 
  dataset_dir: data/humpback-whale-identification
  checkpoint_path: runs/lightning_logs/version_0/checkpoints
  embeddings_db_path: runs/lightning_logs/version_0/emb_db.pth
  save_path: runs/lightning_logs/version_0/prediction.csv
  device: cuda:1
  batch_size: 512
  threshold: 0.85
