data: 
  data_dir: data/humpback-whale-identification

train:
  data: 
    data_dir: data/humpback-whale-identification

  net:
    backbone_name: levit_384
    pretrained: true
    embedding_size: 768
    num_classes: 5000

  loss:
    num_classes: 5000
    embedding_size: 768
    margin: 28.6
    scale: 64

  trainer: 
    devices:
    logger: tensorboard
    max_epochs: 1
    enable_checkpointing: false
    enable_progress_bar: true
    accumulate_grad_batches: 1
    gradient_clip_val: 
    default_root_dir: runs/


  seed: 42
  head_lr: 0.001
  backbone_lr: 0.0001
  batch_size: 8


