data: 
  data_dir: data/humpback-whale-identification

train:
  data: 
    data_dir: data/humpback-whale-identification

  net:
    backbone_name: levit_384
    pretrained: true
    embedding_size: 768
    num_classes: 5000

  loss:
    loss_params:
      num_classes: 5000
      embedding_size: 768
      margin: 28.6
      scale: 64

  seed: 42
  device: cuda:1
  n_epochs: 5
  head_lr: 0.001
  backbone_lr: 0.0001


