version: '3.8'

services:
  app:
    build: .
    image: pythondestroyer/simple_ml_project_with_ci_cd:latest
    command: pytest --skip-slow # remove skip-slow if want to test training phase too
    volumes: 
      - ./data/:/app/data
      - ./runs:/app/runs
